// src/utils/seedRecipes.js
// Temporary script to seed recipe data into Firestore
// Includes both Melbourne-focused and international recipes

import { doc, setDoc } from 'firebase/firestore'
import { db } from '@/firebase/init'

// Melbourne-focused + International recipe sample data
const recipes = [
  // Melbourne-focused recipes
  {
    id: 'recipe_aus_001',
    recipeId: 'recipe_aus_001',
    title: 'Aussie Meat Pie',
    description:
      'Traditional Australian meat pie with rich gravy and flaky pastry. A Melbourne favorite!',
    image: 'https://images.unsplash.com/photo-1601000938259-9e92002320b2?w=800&q=80',
    author: {
      name: 'Tomoki Sakamoto',
      country: 'Australia',
      university: 'Monash University',
    },
    category: 'Main Course',
    cuisine: 'Australian',
    difficulty: 'Medium',
    cookingTime: '45 minutes',
    prepTime: '20 minutes',
    servings: 4,
    tags: ['savory', 'pie', 'beef', 'comfort food'],
    ingredients: [
      '500g beef mince',
      '2 sheets puff pastry',
      '1 onion, diced',
      '2 cups beef stock',
      '2 tbsp Worcestershire sauce',
      '2 tbsp tomato paste',
      '2 tbsp plain flour',
    ],
    instructions: [
      'Brown the mince and onion in a large pan',
      'Add flour and stir for 1 minute',
      'Add stock, Worcestershire sauce, and tomato paste',
      'Simmer for 20 minutes until thick',
      'Line pie tins with pastry, add filling, top with pastry',
      'Bake at 200°C for 25-30 minutes until golden',
    ],
    nutritionInfo: {
      calories: 580,
      protein: '28g',
      carbs: '42g',
      fat: '32g',
    },
    createdAt: '2024-09-15',
  },
  {
    id: 'recipe_aus_002',
    recipeId: 'recipe_aus_002',
    title: 'Lamington Cake',
    description:
      'Classic Australian sponge cake coated in chocolate and coconut. Perfect for afternoon tea!',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80',
    author: {
      name: 'Sarah Chen',
      country: 'Australia',
      university: 'Melbourne University',
    },
    category: 'Dessert',
    cuisine: 'Australian',
    difficulty: 'Medium',
    cookingTime: '60 minutes',
    prepTime: '30 minutes',
    servings: 12,
    tags: ['dessert', 'chocolate', 'coconut', 'sweet'],
    ingredients: [
      '1 sponge cake (store-bought or homemade)',
      '200g dark chocolate',
      '2 cups desiccated coconut',
      '100g butter',
      '1 cup icing sugar',
      '1/3 cup milk',
    ],
    instructions: [
      'Cut sponge cake into squares',
      'Melt chocolate, butter, and icing sugar with milk',
      'Dip each cake square in chocolate mixture',
      'Roll immediately in coconut',
      'Place on wire rack to set',
      'Refrigerate for 30 minutes before serving',
    ],
    nutritionInfo: {
      calories: 320,
      protein: '4g',
      carbs: '38g',
      fat: '18g',
    },
    createdAt: '2024-09-22',
  },
  // Original international recipes from JSON
  {
    id: 'recipe_001',
    recipeId: 'recipe_001',
    title: 'Authentic Japanese Ramen',
    description: 'Rich and flavorful tonkotsu ramen with tender pork and perfect noodles',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80',
    author: {
      name: 'Takeshi Yamada',
      country: 'Japan',
      university: 'Tokyo University',
    },
    category: 'Main Course',
    cuisine: 'Japanese',
    difficulty: 'Medium',
    cookingTime: '45 minutes',
    prepTime: '30 minutes',
    servings: 4,
    tags: ['comfort food', 'soup', 'noodles', 'pork'],
    ingredients: [
      '500g pork bones (for broth)',
      '200g miso paste',
      '300g fresh ramen noodles',
      '2 soft-boiled eggs',
      '100g chashu pork slices',
      '2 green onions, chopped',
      '1 sheet nori seaweed',
      '1 clove garlic, minced',
      '1 tsp sesame oil',
    ],
    instructions: [
      'Boil pork bones in water for 4 hours to make rich broth',
      'Mix miso paste with hot broth until well combined',
      'Cook ramen noodles according to package instructions',
      'Prepare soft-boiled eggs and slice chashu pork',
      'Assemble bowl with noodles, pour hot broth over',
      'Top with egg, pork, green onions, and nori',
      'Drizzle with sesame oil and serve immediately',
    ],
    nutritionInfo: {
      calories: 650,
      protein: '35g',
      carbs: '45g',
      fat: '28g',
    },
    createdAt: '2024-01-15',
  },
  {
    id: 'recipe_002',
    recipeId: 'recipe_002',
    title: 'Spicy Korean Kimchi Fried Rice',
    description: 'Delicious fried rice with fermented kimchi and vegetables',
    image: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800&q=80',
    author: {
      name: 'Min-jun Kim',
      country: 'South Korea',
      university: 'Melbourne University',
    },
    category: 'Main Course',
    cuisine: 'Korean',
    difficulty: 'Easy',
    cookingTime: '20 minutes',
    prepTime: '15 minutes',
    servings: 2,
    tags: ['spicy', 'vegetarian', 'quick meal', 'comfort food'],
    ingredients: [
      '2 cups cooked rice (preferably day-old)',
      '1 cup kimchi, chopped',
      '2 eggs',
      '2 tbsp vegetable oil',
      '1 onion, diced',
      '2 cloves garlic, minced',
      '1 tbsp soy sauce',
      '1 tsp sesame oil',
      '2 green onions, chopped',
      '1 tsp gochugaru (Korean chili flakes)',
    ],
    instructions: [
      'Heat vegetable oil in a large pan or wok',
      'Sauté onion and garlic until fragrant',
      'Add chopped kimchi and cook for 3 minutes',
      'Add rice and mix well, breaking up clumps',
      'Season with soy sauce and gochugaru',
      'Push rice to one side, scramble eggs on the other',
      'Mix everything together and cook for 2 more minutes',
      'Garnish with green onions and drizzle sesame oil',
    ],
    nutritionInfo: {
      calories: 420,
      protein: '12g',
      carbs: '58g',
      fat: '15g',
    },
    createdAt: '2024-01-20',
  },
  {
    id: 'recipe_003',
    recipeId: 'recipe_003',
    title: 'Thai Green Curry with Chicken',
    description: 'Aromatic and creamy green curry with tender chicken and vegetables',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80',
    author: {
      name: 'Pranee Suwannakul',
      country: 'Thailand',
      university: 'Monash University',
    },
    category: 'Main Course',
    cuisine: 'Thai',
    difficulty: 'Medium',
    cookingTime: '35 minutes',
    prepTime: '20 minutes',
    servings: 4,
    tags: ['spicy', 'coconut', 'curry', 'chicken'],
    ingredients: [
      '500g chicken breast, sliced',
      '400ml coconut milk',
      '3 tbsp green curry paste',
      '1 eggplant, cubed',
      '100g green beans, trimmed',
      '1 red bell pepper, sliced',
      '2 tbsp fish sauce',
      '1 tbsp palm sugar',
      '4 Thai basil leaves',
      '2 kaffir lime leaves',
      '1 red chili, sliced',
    ],
    instructions: [
      'Heat 1/3 of coconut milk in a large pan',
      'Add green curry paste and fry until fragrant',
      'Add chicken and cook until no longer pink',
      'Pour in remaining coconut milk and bring to simmer',
      'Add eggplant, green beans, and bell pepper',
      'Season with fish sauce and palm sugar',
      'Add lime leaves and simmer for 10 minutes',
      'Garnish with basil and chili before serving',
    ],
    nutritionInfo: {
      calories: 380,
      protein: '28g',
      carbs: '15g',
      fat: '25g',
    },
    createdAt: '2024-02-01',
  },
  {
    id: 'recipe_004',
    recipeId: 'recipe_004',
    title: 'Indian Butter Chicken (Murgh Makhani)',
    description: 'Creamy and rich tomato-based curry with tender chicken pieces',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    author: {
      name: 'Priya Sharma',
      country: 'India',
      university: 'Deakin University',
    },
    category: 'Main Course',
    cuisine: 'Indian',
    difficulty: 'Medium',
    cookingTime: '40 minutes',
    prepTime: '30 minutes',
    servings: 4,
    tags: ['creamy', 'tomato', 'curry', 'chicken'],
    ingredients: [
      '600g chicken thighs, cubed',
      '400g canned tomatoes',
      '200ml heavy cream',
      '1 large onion, diced',
      '4 cloves garlic, minced',
      '1 inch ginger, grated',
      '2 tbsp butter',
      '1 tsp garam masala',
      '1 tsp cumin powder',
      '1 tsp coriander powder',
      '1/2 tsp turmeric',
      'Salt to taste',
    ],
    instructions: [
      'Marinate chicken with salt and turmeric for 20 minutes',
      'Heat butter in a large pan and sauté onions until golden',
      'Add garlic and ginger, cook for 2 minutes',
      'Add spices and cook until fragrant',
      'Add tomatoes and simmer for 15 minutes',
      'Blend the sauce until smooth and return to pan',
      'Add chicken and cook for 15 minutes',
      'Stir in cream and simmer for 5 more minutes',
    ],
    nutritionInfo: {
      calories: 450,
      protein: '32g',
      carbs: '12g',
      fat: '28g',
    },
    createdAt: '2024-02-05',
  },
  {
    id: 'recipe_005',
    recipeId: 'recipe_005',
    title: 'Chinese Mapo Tofu',
    description: 'Spicy Sichuan tofu dish with minced pork in aromatic sauce',
    image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&q=80',
    author: {
      name: 'Wei Chen',
      country: 'China',
      university: 'Melbourne University',
    },
    category: 'Main Course',
    cuisine: 'Chinese',
    difficulty: 'Easy',
    cookingTime: '25 minutes',
    prepTime: '15 minutes',
    servings: 3,
    tags: ['spicy', 'tofu', 'pork', 'sichuan'],
    ingredients: [
      '400g silken tofu, cubed',
      '150g ground pork',
      '2 tbsp doubanjiang (fermented bean paste)',
      '1 tbsp soy sauce',
      '1 tsp sugar',
      '1/2 cup chicken stock',
      '2 cloves garlic, minced',
      '1 tbsp cornstarch mixed with water',
      '2 green onions, chopped',
      '1 tsp Sichuan peppercorns',
      '2 tbsp vegetable oil',
    ],
    instructions: [
      'Heat oil in wok and add Sichuan peppercorns',
      'Add ground pork and cook until browned',
      'Add garlic and doubanjiang, stir-fry for 1 minute',
      'Add soy sauce, sugar, and chicken stock',
      'Gently add tofu cubes and simmer for 5 minutes',
      'Thicken with cornstarch mixture',
      'Garnish with green onions before serving',
      'Serve hot with steamed rice',
    ],
    nutritionInfo: {
      calories: 320,
      protein: '22g',
      carbs: '8g',
      fat: '20g',
    },
    createdAt: '2024-02-08',
  },
  {
    id: 'recipe_006',
    recipeId: 'recipe_006',
    title: 'Vietnamese Pho Bo',
    description: 'Traditional beef noodle soup with aromatic herbs and spices',
    image: 'https://images.unsplash.com/photo-1559847844-d9dddac2e6cb?w=800&q=80',
    author: {
      name: 'Linh Nguyen',
      country: 'Vietnam',
      university: 'Monash University',
    },
    category: 'Main Course',
    cuisine: 'Vietnamese',
    difficulty: 'Hard',
    cookingTime: '3 hours',
    prepTime: '30 minutes',
    servings: 6,
    tags: ['soup', 'beef', 'noodles', 'herbs'],
    ingredients: [
      '1kg beef bones',
      '500g beef brisket',
      '200g rice noodles (banh pho)',
      '1 large onion, halved',
      '5cm piece ginger',
      '3 star anise',
      '1 cinnamon stick',
      '3 cardamom pods',
      '1 tbsp coriander seeds',
      'Fresh herbs (cilantro, mint, Thai basil)',
      'Bean sprouts',
      'Lime wedges',
      'Fish sauce and hoisin sauce',
    ],
    instructions: [
      'Char onion and ginger over open flame until blackened',
      'Toast spices in dry pan until fragrant',
      'Boil bones and brisket, then drain and rinse',
      'Return to pot with charred vegetables and spices',
      'Simmer for 3 hours, skimming foam regularly',
      'Strain broth and season with fish sauce',
      'Cook rice noodles according to package instructions',
      'Slice brisket thinly and serve with noodles in hot broth',
      'Garnish with herbs, bean sprouts, and lime',
    ],
    nutritionInfo: {
      calories: 380,
      protein: '25g',
      carbs: '35g',
      fat: '12g',
    },
    createdAt: '2024-02-12',
  },
  {
    id: 'recipe_007',
    recipeId: 'recipe_007',
    title: 'Indonesian Nasi Goreng',
    description: 'Fragrant fried rice with sweet soy sauce and topped with fried egg',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80',
    author: {
      name: 'Sari Dewi',
      country: 'Indonesia',
      university: 'RMIT University',
    },
    category: 'Main Course',
    cuisine: 'Indonesian',
    difficulty: 'Easy',
    cookingTime: '20 minutes',
    prepTime: '15 minutes',
    servings: 2,
    tags: ['fried rice', 'sweet soy sauce', 'egg', 'shrimp'],
    ingredients: [
      '2 cups cooked jasmine rice',
      '200g shrimp, peeled',
      '2 eggs',
      '3 tbsp kecap manis (sweet soy sauce)',
      '2 tbsp vegetable oil',
      '3 shallots, sliced',
      '3 cloves garlic, minced',
      '2 red chilies, sliced',
      '1 tbsp tamarind paste',
      'Fried shallots for garnish',
      'Cucumber slices for serving',
    ],
    instructions: [
      'Heat oil in large wok or pan',
      'Fry shallots, garlic, and chilies until fragrant',
      'Add shrimp and cook until pink',
      'Push to one side, scramble eggs on the other',
      'Add rice and mix everything together',
      'Season with kecap manis and tamarind paste',
      'Stir-fry for 3-4 minutes until well combined',
      'Garnish with fried shallots and serve with cucumber',
    ],
    nutritionInfo: {
      calories: 480,
      protein: '24g',
      carbs: '52g',
      fat: '18g',
    },
    createdAt: '2024-02-15',
  },
  {
    id: 'recipe_008',
    recipeId: 'recipe_008',
    title: 'Malaysian Laksa',
    description: 'Spicy coconut curry noodle soup with seafood and vegetables',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80',
    author: {
      name: 'Ahmad Rahman',
      country: 'Malaysia',
      university: 'RMIT University',
    },
    category: 'Main Course',
    cuisine: 'Malaysian',
    difficulty: 'Medium',
    cookingTime: '40 minutes',
    prepTime: '25 minutes',
    servings: 4,
    tags: ['spicy', 'coconut', 'seafood', 'noodles'],
    ingredients: [
      '300g rice vermicelli',
      '400ml coconut milk',
      '200g prawns',
      '200g fish fillet, cubed',
      '2 tbsp laksa paste',
      '1 cup bean sprouts',
      '2 boiled eggs, halved',
      'Fresh herbs (cilantro, mint)',
      '2 tbsp tamarind paste',
      '1 tbsp palm sugar',
      'Fish sauce to taste',
    ],
    instructions: [
      'Soak rice vermicelli in hot water until soft',
      'Heat coconut milk in large pot',
      'Add laksa paste and stir until fragrant',
      'Add prawns and fish, cook for 5 minutes',
      'Season with tamarind, palm sugar, and fish sauce',
      'Add bean sprouts and cook for 2 minutes',
      'Divide noodles among bowls',
      'Ladle hot soup over noodles',
      'Top with egg halves and fresh herbs',
    ],
    nutritionInfo: {
      calories: 420,
      protein: '26g',
      carbs: '38g',
      fat: '18g',
    },
    createdAt: '2024-02-18',
  },
]

/**
 * Seed recipes to Firestore
 * This is a temporary function for development/testing
 */
export const seedRecipes = async () => {
  try {
    console.log('🌱 Starting to seed recipes to Firestore...')
    console.log(`📦 Total recipes to add: ${recipes.length}`)

    let successCount = 0
    let errorCount = 0

    // Add each recipe to Firestore
    for (const recipe of recipes) {
      try {
        // Use 'id' field as document ID for consistency
        await setDoc(doc(db, 'recipes', recipe.id), recipe)
        console.log(`✅ Added recipe: ${recipe.title} (ID: ${recipe.id})`)
        successCount++
      } catch (error) {
        console.error(`❌ Error adding recipe ${recipe.title}:`, error)
        errorCount++
      }
    }

    console.log('\n📊 Seeding Summary:')
    console.log(`   ✅ Success: ${successCount} recipes`)
    console.log(`   ❌ Errors: ${errorCount} recipes`)
    console.log('\n🎉 Recipe seeding completed!')

    return { success: successCount, errors: errorCount }
  } catch (error) {
    console.error('❌ Fatal error during seeding:', error)
    throw error
  }
}

// Export individual recipes for testing
export { recipes }
